### ISSUE TITLE
Add dedicated parameter for width of random in-cluster distribution

### ISSUE THREAD

**Issue by wenzeslaus** [ncsu-landscape-dynamics/pathways-simulation#43]
The current:

```
  arrangement: clustered
  clustered:
    max_stems_per_cluster: 400
    distribution: random
    parameters:
    - 800
```

Should be something like:

```
  arrangement: clustered
  clustered:
    max_stems_per_cluster: 400
    distribution: random
    width: 800
```

However, this needs to be synchronized with #13 and #8 because of the similar naming and meaning.
