### ISSUE TITLE
Overlapping clusters lower the resulting infestation rate

### ISSUE THREAD

**Issue by wenzeslaus** [ncsu-landscape-dynamics/pathways-simulation#8]
This happens if there is more than one cluster. The clusters can now overlap as they are placed to the list of stems. This potentially (and practically often) results in a lower number of infested stems and thus lower resulting infestation rate (aka `true_infestation_rate`). This happens regardless of the distribution of infested stems within the cluster as visible from example with `distribution: random` from #6 (same result also for much larger simulations):

```
pest:
  infestation_rate:
    distribution: fixed_value
    value: 0.05
  arrangement: clustered
  clustered:
    max_stems_per_cluster: 10
    distribution: random
    parameters:
    - 10
```

```
$ python3 -m pathways --num-shipments 50 --num-simulations=100 --config-file config.yml --seed 1
...
true_infestation_rate: 0.049
```

The solution is probably recording range for each cluster, checking if new cluster overlaps and changing its position if needed. Checking the available spots (intervals) might be helpful. A "too many iterations" check will be needed.
